-- Run this in the Supabase SQL editor (Project > SQL Editor > New query).
-- Adds a taxonomy for categories (e.g. Transport, Groceries) and a
-- `subcategory` text column on transactions. `categories` exists purely to
-- give each category a stable id/color; it is not referenced by a foreign
-- key from transactions, matching this app's existing pattern of `category`
-- as plain text with no relational integrity. RLS is left disabled to match
-- the (RLS-off) `transactions` table.
--
-- Sub-categories deliberately have no table of their own: a sub-category has
-- no data beyond its name (its color is always a shade derived from the
-- parent category's color, and it has no existence independent of a
-- transaction, since creating one always immediately assigns it). Instead,
-- "known sub-categories per category" is derived at read time from distinct
-- transactions.subcategory values (see src/categoriesApi.ts).

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null,
  created_at timestamptz not null default now()
);

alter table public.transactions add column if not exists subcategory text;

-- Seed the 8 existing built-in categories with their current hardcoded hex
-- colors, in the same order as today's CATEGORIES const, so ids 1-8 preserve
-- today's chip order when the app orders by id.
insert into public.categories (name, color) values
  ('Transport', '#3d9eff'), ('Groceries', '#52b788'), ('Food', '#f59e0b'),
  ('Shopping', '#c084fc'), ('Entertainment', '#f472b6'), ('Bills', '#ef4444'),
  ('Travel', '#22d3ee'), ('Other', '#8b9cb3')
on conflict (name) do nothing;

-- NOTE: this unique constraint is case-sensitive ("Transport" vs "transport"
-- would not collide here). The app enforces case-insensitive dedupe itself
-- (an ilike check before insert) — this constraint is only a last-resort
-- safety net against exact-duplicate races.
