-- Run this in the Supabase SQL editor (Project > SQL Editor > New query).
-- Creates the transaction_items table (many item rows per transaction,
-- e.g. every product in a £100 Tesco shop) linked to transactions with a
-- cascade-deleting foreign key. The app's receipt OCR and manual item
-- entry both write here; until this table exists those writes fail.

create table if not exists public.transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id text not null,
  name text not null,
  price_cents integer not null,
  created_at timestamptz not null default now()
);

-- Idempotent whether the table pre-existed or was just created above.
alter table public.transaction_items
  drop constraint if exists transaction_items_transaction_id_fkey;

alter table public.transaction_items
  add constraint transaction_items_transaction_id_fkey
  foreign key (transaction_id) references public.transactions(id)
  on delete cascade;

create index if not exists transaction_items_transaction_idx
  on public.transaction_items (transaction_id);
